// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALYbL_u3jvgDP9bMRc7AUEV433Fk21Rpk',
    appId: '1:193434852634:web:87f1bbfcefcb9fbf96e0a3',
    messagingSenderId: '193434852634',
    projectId: 'book-store-266a9',
    authDomain: 'book-store-266a9.firebaseapp.com',
    storageBucket: 'book-store-266a9.firebasestorage.app',
    measurementId: 'G-EL6GZS6WL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2NDC5wJqHkG5d-2RzeMEYuKAU9YlrBQ8',
    appId: '1:193434852634:android:d5e90fed1ac3680d96e0a3',
    messagingSenderId: '193434852634',
    projectId: 'book-store-266a9',
    storageBucket: 'book-store-266a9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALYbL_u3jvgDP9bMRc7AUEV433Fk21Rpk',
    appId: '1:193434852634:web:cff679b95a8e3c6296e0a3',
    messagingSenderId: '193434852634',
    projectId: 'book-store-266a9',
    authDomain: 'book-store-266a9.firebaseapp.com',
    storageBucket: 'book-store-266a9.firebasestorage.app',
    measurementId: 'G-EQ041WZ5Z1',
  );

}